name = "Createrency"
author = "Harvel"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2693bbe73c6b242cb65056472a10a71abbaa857a1617f88d54164b90d424cdae"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
