name = "Createrency"
author = "Harvel"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e356142ecfd710a5b08f6d041d1f9d03ad2ad690ed44d6cefdfd07c5daf74e82"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
