name = "Sugar"
author = "Harvel"
version = "4.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "241f97eeabc252e515c3d187794a38529b09398754cef679f968a855e1ea660d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1"]
