name = "Createrency"
author = "Harvel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd733526f39f1bf57700fab9315de2c7a90044cb11e760cc42033201fa466e52"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
