name = "Createrency"
author = "Harvel"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "713978c2df1623e16f352adc97a6d1e4b57f9258481e9215aa5f6011ac69b6b1"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
