version = 1
enableSodiumMenu = false
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 32
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
createdeco = true
createaddition = true
sliceanddice = true
create = true
create_dd = true
railways = true
createrailwaysnavigator = true
milk = true
dragonlib = true
createframed = true
interiors = true
chisel = true
another_furniture = true
toms_storage = true
minecraft = true
creategoggles = true
